import {
  AlignLeft,
  ArrowLeft,
  ArrowRight,
  BookCopy,
  BookOpen,
  BookPlus,
  BrainCircuit,
  Briefcase,
  Check,
  ChevronDown,
  FileText,
  FolderTree,
  GripVertical,
  Heading,
  Heart,
  Lightbulb,
  ListTree,
  Loader2,
  Maximize2,
  Megaphone,
  MessagesSquare,
  Minimize2,
  PenLine,
  Plus,
  RefreshCw,
  ShieldCheck,
  Sparkles,
  Tags,
  Trash2,
  UserRound,
  Waves,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  AlignLeft,
  ArrowLeft,
  ArrowRight,
  BookCopy,
  BookOpen,
  BookPlus,
  BrainCircuit,
  Briefcase,
  Check,
  ChevronDown,
  FileText,
  FolderTree,
  GripVertical,
  Heading,
  Heart,
  Lightbulb,
  ListTree,
  Loader2,
  Maximize2,
  Megaphone,
  MessagesSquare,
  Minimize2,
  PenLine,
  Plus,
  RefreshCw,
  ShieldCheck,
  Sparkles,
  Tags,
  Trash2,
  UserRound,
  Waves,
};

/** Render a lucide icon by name (names stored in constants). */
export function Icon({ name, className }: { name: string; className?: string }) {
  const Cmp = MAP[name] ?? Sparkles;
  return <Cmp className={className} aria-hidden />;
}
